language: ruby
rvm:
  - 2.4
services:
  - postgresql
test:
  adapter: postgresql
  database: photo-app-test
before_script:
  - cp config/database.yml.travis config/database.yml

before_install:
- gem update --system
- gem --version
