language: ruby
rvm:
  - 2.4
services:
  - postgresql
test:
  adapter: postgresql
  database: photo-app-test
before_script:
  - "psql -c 'create database photo_app_test' -U postgres"
  - "bundle exec rake db:migrate"
before_install:
- gem update --system
- gem install bundler
