language: ruby
rvm:
  - 2.4
services:
  - postgresql
test:
  adapter: postgresql
  database: photo-app-test
before_script:
  - psql -U postgres -c "create database 'photo-app-test'"

before_install:
- gem update --system
- gem install bundler
